import { fontMono, fontSans } from '@/config/font';
import '@/styles/globals.css';
import cn from '@/utils';
import type { Metadata } from 'next';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'TripWise',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' data-theme='corporate' suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen font-sans antialiased',
          fontSans.variable,
          fontMono.variable,
        )}
      >
        <main className='relative'>{children}</main>
        <Toaster position='top-right' />
      </body>
    </html>
  );
}
